version: "3.9"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  app:
    build: *dockerfile-dev-build
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    command: [
      "scripts/start-dev.sh"
    ]
