# Generated by Django 4.2.2 on 2023-06-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_player1", models.IntegerField(default=0)),
                ("points_player2", models.IntegerField(default=0)),
                ("last_action", models.CharField(max_length=100)),
                ("next_action", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "result",
                    models.IntegerField(
                        choices=[
                            (1, "Playing"),
                            (2, "Player1Win"),
                            (3, "Player2Win"),
                            (4, "Draw"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("who_starts", models.IntegerField(default=1)),
                ("points_in_game", models.IntegerField(default=1)),
                ("points_being_raised", models.IntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card", models.CharField(max_length=2)),
                ("played", models.BooleanField(default=False)),
                (
                    "hand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.hand",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.round"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hand",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.round"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player1",
                to="core.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player2",
                to="core.player",
            ),
        ),
    ]
