# Generated by Django 4.2.2 on 2023-06-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_game_points_player1_alter_game_points_player2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("is_current", models.BooleanField(default=True)),
                (
                    "result",
                    models.IntegerField(
                        choices=[
                            (1, "Playing"),
                            (2, "Player1Win"),
                            (3, "Player2Win"),
                            (4, "Draw"),
                        ]
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.round"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card", models.CharField(max_length=2)),
                ("played", models.BooleanField(default=False)),
                (
                    "hand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.hand",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
    ]
